<a href="https://colab.research.google.com/github/Pablo-app-developer/CURSO-MANIPULACION-Y-TRANFORMACION-DE-DATOS-CON-PANDAS-Y-NUM/blob/main/dimentions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importar librería

In [ ]:
import numpy as np

## Definiendo arrays

In [ ]:
scalar = np.array(42)
print(scalar)
print("tiene",scalar.ndim, "dimensiones")

42
tiene 0 dimensiones


In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim


[[1 2 3]
 [4 5 6]]


2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

ndmin: nos sirve para definir la cantidad de dimensiones de 1 array

In [ ]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

np.expand_dims: nos ayuda a expandir la cantidad de dimensiones

axis=0 para filas
axis=1 para columnas

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

np.squeeze : nos sirve para darle la dimensionalidad precisa a un array, de acuerdo con los datos que contiene.

In [ ]:
print(vector, vector.ndim)
# ahora vamos a darle la cantidad óptima de dimensiones
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
